### ISSUE TITLE
Add import json to example /  I needed to change   ws: Any to ws: any

### ISSUE THREAD

**Issue by broswell** [Leggin/dirigera#5]
Thanks for writing this!  Works great to read my new Ikea Vindstyrka air quality monitor via Dirigera.

Consider adding 
import json to your example.

Not sure why (I tried to understand) by when I ran sample using Python 3.10 I got 
NameError: name 'Any' is not defined.  Did you mean: 'any'?

I changed Any to any, and I am successfully pulling data!

**Comment by Leggin** [comment]
Thanks for the input, I will add import json.
Regarding the issue with Any, it's a similar problem I will add `from typing import Any`.

_Using any is not correct here since it is a [function ](https://www.w3schools.com/python/ref_func_any.asp). Python doesnt complain though because it doesnt check types. You would need to run mypy to see the problem._
